#mmAutoEmbedShellcode - python 2.7.16
#Converts a given bin file to bytes using the pveReadBin perl script by Peter Van Eeckhoutte
#It then adds the bytes into a character array and simple default C file that can be used
#   to call the converted bin file.

import subprocess
import sys

if len(sys.argv) < 2:
    print("Usage: python mmAutoBinEmbed.py [bin file to embed]")
    print("Note: Enter the full path to the bin file if it is not in the same folder as the script.")
    exit()

binFile = sys.argv[1]
outputFile = "default.c"
perl = subprocess.Popen(["perl", "pveReadBin.pl", binFile], stdout=subprocess.PIPE)

f = open("default.c", "w")
f.write("//Autogenerated shellcode tester. Use this to test your shellcode.\n")
f.write("\n\n")
f.write("char shellcode[] = ")
data = perl.stdout.readline()
while data:
    if(data[0] == "\""):
        f.write(data)
    data = perl.stdout.readline()
f.write("int main(int argc, char **argv){\n\n")
f.write("\tint (*func)();\n\n")
f.write("\tfunc = (int (*)()) shellcode;\n\n")
f.write("\t(int)(*func)();\n\n")
f.write("}")
f.close()